import { useState, useCallback, useEffect } from 'react'
import { Plus, Pencil, Trash2, ExternalLink, Calendar, Hash } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Modal } from '@/components/common/Modal'
import { ConfirmDialog } from '@/components/common/ConfirmDialog'
import { FormField, Input, Textarea, Select, ErrorAlert, EmptyState, LoadingState } from '@/components/common/FormField'
import { useTable, useCrud } from '@/hooks/useTable'
import { edicaoService } from '@/lib/db'

const STATUS_OPTS = [
  { value: 'ativo', label: 'Ativo' },
  { value: 'encerrado', label: 'Encerrado' },
  { value: 'planejado', label: 'Planejado' },
]

const STATUS_VARIANT = {
  ativo: 'success', encerrado: 'secondary', planejado: 'default',
}

const EMPTY = {
  ano_referencia: new Date().getFullYear(),
  numero_edital: '',
  programa_id: 'PIBICJR',
  codigo_facitec: '',
  status: 'planejado',
  data_inicio: '',
  data_termino: '',
  edital_url: '',
  observacoes: '',
  numero_processo: '',
  prazo_recurso_fim: '',
  item_criterios_avaliacao: '',
}

function codigoFromAno(ano) {
  return ano ? `PIBICJR-${ano}` : ''
}

function EdicaoForm({ value, onChange }) {
  const set = (k) => (e) => onChange({ ...value, [k]: e.target.value })

  // Auto-fill codigo_facitec when ano_referencia changes
  function handleAnoChange(e) {
    const ano = e.target.value
    const codigoAtual = value.codigo_facitec ?? ''
    // Only auto-update if the field is empty or was previously auto-generated
    const wasAutoGenerated = !codigoAtual || /^PIBICJR-\d{4}$/.test(codigoAtual)
    onChange({
      ...value,
      ano_referencia: ano,
      codigo_facitec: wasAutoGenerated ? codigoFromAno(ano) : codigoAtual,
    })
  }

  return (
    <div className="space-y-4">
      {/* Row 1: Ano + Programa */}
      <div className="grid grid-cols-2 gap-3">
        <FormField label="Ano de referência" required>
          <Input
            type="number"
            min="2000"
            max="2099"
            placeholder="2026"
            value={value.ano_referencia ?? ''}
            onChange={handleAnoChange}
          />
        </FormField>
        <FormField label="Programa">
          <Input
            placeholder="PIBICJR"
            value={value.programa_id ?? ''}
            onChange={set('programa_id')}
          />
        </FormField>
      </div>

      {/* Row 2: Número edital + Código FACITEC */}
      <div className="grid grid-cols-2 gap-3">
        <FormField label="Número do edital">
          <Input
            placeholder="01/2026"
            value={value.numero_edital ?? ''}
            onChange={set('numero_edital')}
          />
        </FormField>
        <FormField label="Código FACITEC">
          <Input
            placeholder="PIBICJR-2026"
            value={value.codigo_facitec ?? ''}
            onChange={set('codigo_facitec')}
          />
        </FormField>
      </div>

      {/* Row 3: Número do processo + Item dos critérios */}
      <div className="grid grid-cols-2 gap-3">
        <FormField label="Número do processo">
          <Input
            placeholder="ex: 2026.001234"
            value={value.numero_processo ?? ''}
            onChange={set('numero_processo')}
          />
        </FormField>
        <FormField label="Item dos critérios de avaliação">
          <Input
            placeholder="ex: 8.1"
            value={value.item_criterios_avaliacao ?? ''}
            onChange={set('item_criterios_avaliacao')}
          />
        </FormField>
      </div>

      {/* Row 4: Status */}
      <FormField label="Status" required>
        <Select value={value.status} onChange={set('status')}>
          {STATUS_OPTS.map(s => (
            <option key={s.value} value={s.value}>{s.label}</option>
          ))}
        </Select>
      </FormField>

      {/* Row 5: Datas */}
      <div className="grid grid-cols-2 gap-3">
        <FormField label="Data de início">
          <Input type="date" value={value.data_inicio ?? ''} onChange={set('data_inicio')} />
        </FormField>
        <FormField label="Data de término">
          <Input type="date" value={value.data_termino ?? ''} onChange={set('data_termino')} />
        </FormField>
      </div>

      {/* Prazo final para recursos */}
      <FormField label="Prazo final para recursos">
        <Input
          type="date"
          value={value.prazo_recurso_fim ?? ''}
          onChange={set('prazo_recurso_fim')}
        />
      </FormField>

      {/* URL do edital */}
      <FormField label="URL do edital">
        <Input
          type="url"
          placeholder="https://..."
          value={value.edital_url ?? ''}
          onChange={set('edital_url')}
        />
      </FormField>

      {/* Observações */}
      <FormField label="Observações">
        <Textarea
          placeholder="Observações sobre a edição..."
          value={value.observacoes ?? ''}
          onChange={set('observacoes')}
          rows={3}
        />
      </FormField>
    </div>
  )
}

function fmt(d) {
  if (!d) return '—'
  return new Date(d).toLocaleDateString('pt-BR')
}

export function Edicoes() {
  const fetch = useCallback(() => edicaoService.list(), [])
  const { data, loading, error, reload } = useTable(fetch)
  const { saving, crudError, create, update, remove } = useCrud(edicaoService)

  const [modal, setModal] = useState(null)
  const [form, setForm] = useState(EMPTY)
  const [confirm, setConfirm] = useState(null)

  function openCreate() {
    const ano = new Date().getFullYear()
    setForm({ ...EMPTY, ano_referencia: ano, codigo_facitec: codigoFromAno(ano) })
    setModal({ mode: 'create' })
  }

  function openEdit(item) {
    setForm({
      ...EMPTY,
      ...item,
      ano_referencia: item.ano_referencia ?? '',
      numero_edital: item.numero_edital ?? '',
      programa_id: item.programa_id ?? 'PIBICJR',
      codigo_facitec: item.codigo_facitec ?? '',
      data_inicio: item.data_inicio ?? '',
      data_termino: item.data_termino ?? '',
      edital_url: item.edital_url ?? '',
      observacoes: item.observacoes ?? '',
      numero_processo: item.numero_processo ?? '',
      prazo_recurso_fim: item.prazo_recurso_fim ?? '',
      item_criterios_avaliacao: item.item_criterios_avaliacao ?? '',
    })
    setModal({ mode: 'edit', item })
  }

  function closeModal() { setModal(null) }

  async function handleSubmit(e) {
    e.preventDefault()
    const payload = {
      ano_referencia: form.ano_referencia ? Number(form.ano_referencia) : null,
      numero_edital: form.numero_edital || null,
      programa_id: form.programa_id || null,
      codigo_facitec: form.codigo_facitec || null,
      status: form.status,
      data_inicio: form.data_inicio || null,
      data_termino: form.data_termino || null,
      edital_url: form.edital_url || null,
      observacoes: form.observacoes || null,
      numero_processo: form.numero_processo || null,
      prazo_recurso_fim: form.prazo_recurso_fim || null,
      item_criterios_avaliacao: form.item_criterios_avaliacao || null,
    }
    try {
      if (modal.mode === 'create') await create(payload)
      else await update(modal.item.id, payload)
      closeModal()
      reload()
    } catch { /* crudError displayed */ }
  }

  async function handleDelete() {
    try {
      await remove(confirm)
      setConfirm(null)
      reload()
    } catch { /* */ }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">{data.length} edição(ões) cadastrada(s)</p>
        <Button size="sm" onClick={openCreate}>
          <Plus className="w-4 h-4" /> Nova Edição
        </Button>
      </div>

      <ErrorAlert message={error} />

      {loading ? <LoadingState /> : data.length === 0
        ? <EmptyState message="Nenhuma edição cadastrada ainda." />
        : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {data.map((ed) => (
              <Card key={ed.id} className="hover:shadow-md transition-shadow">
                <CardHeader className="pb-2">
                  <div className="flex items-start justify-between gap-2">
                    <div className="space-y-0.5">
                      {ed.codigo_facitec
                        ? <CardTitle className="text-sm font-semibold">{ed.codigo_facitec}</CardTitle>
                        : <CardTitle className="text-sm font-mono text-muted-foreground">#{ed.id}</CardTitle>
                      }
                      {ed.numero_edital && (
                        <p className="text-xs text-muted-foreground flex items-center gap-1">
                          <Hash className="w-3 h-3" />Edital {ed.numero_edital}
                        </p>
                      )}
                    </div>
                    <Badge variant={STATUS_VARIANT[ed.status] ?? 'secondary'}>{ed.status}</Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-2 pt-0">
                  <div className="grid grid-cols-2 gap-x-4 text-sm">
                    {ed.programa_id && (
                      <p className="text-muted-foreground">
                        Programa: <span className="text-foreground font-medium">{ed.programa_id}</span>
                      </p>
                    )}
                    {ed.ano_referencia && (
                      <p className="text-muted-foreground">
                        Ano: <span className="text-foreground font-medium">{ed.ano_referencia}</span>
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-1 text-xs text-muted-foreground">
                    <Calendar className="w-3.5 h-3.5" />
                    <span>{fmt(ed.data_inicio)}</span>
                    {ed.data_termino && <><span>→</span><span>{fmt(ed.data_termino)}</span></>}
                  </div>
                  {ed.observacoes && (
                    <p className="text-xs text-muted-foreground line-clamp-2">{ed.observacoes}</p>
                  )}
                  <div className="flex items-center gap-2 pt-1">
                    {ed.edital_url && (
                      <a href={ed.edital_url} target="_blank" rel="noreferrer">
                        <Button variant="outline" size="sm">
                          <ExternalLink className="w-3.5 h-3.5 mr-1" />Edital
                        </Button>
                      </a>
                    )}
                    <Button variant="outline" size="sm" onClick={() => openEdit(ed)}>
                      <Pencil className="w-3.5 h-3.5 mr-1" />Editar
                    </Button>
                    <Button
                      variant="ghost" size="sm"
                      className="text-destructive hover:text-destructive"
                      onClick={() => setConfirm(ed.id)}
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}

      <Modal
        open={!!modal}
        onClose={closeModal}
        title={modal?.mode === 'create' ? 'Nova Edição' : 'Editar Edição'}
        size="md"
      >
        <form onSubmit={handleSubmit} className="space-y-4">
          <EdicaoForm value={form} onChange={setForm} />
          <ErrorAlert message={crudError} />
          <div className="flex gap-2 justify-end pt-2 border-t border-border">
            <Button type="button" variant="outline" size="sm" onClick={closeModal}>Cancelar</Button>
            <Button type="submit" size="sm" disabled={saving}>
              {saving ? 'Salvando…' : 'Salvar'}
            </Button>
          </div>
        </form>
      </Modal>

      <ConfirmDialog
        open={!!confirm}
        onClose={() => setConfirm(null)}
        onConfirm={handleDelete}
        loading={saving}
        message="A edição e todos os seus dados serão removidos. Deseja continuar?"
      />
    </div>
  )
}
